### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by BrechtA** [pip-install-python/dash_summernote#1]
Hi, I'm getting some exceptions when using dash summernote.
Would be highly appreciated if someone could look into this!

![image](https://github.com/pip-install-python/dash_summernote/assets/5300405/29fd505e-6f0e-4a14-a185-b9d29da185e8)

Traceback (most recent call last):
  File "c:\Users\baudenaert\Anaconda3\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\baudenaert\Anaconda3\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
  File "c:\Users\baudenaert\Anaconda3\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
  File "c:\Users\baudenaert\Anaconda3\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\baudenaert\Anaconda3\lib\site-packages\dash\dash.py", line 923, in serve_component_suites
    _validate.validate_js_path(self.registered_paths, package_name, path_in_pkg)
  File "c:\Users\baudenaert\Anaconda3\lib\site-packages\dash\_validate.py", line 374, in validate_js_path
    raise exceptions.DependencyException(
dash.exceptions.DependencyException: "dash_summernote" is registered but the path requested is not valid.
The path requested: "b293d601cf1cddd1a1b4.ttf"
List of registered paths: defaultdict(<class 'set'>, {'dash': {'dcc/dash_core_components.js', 'deps/react-dom@16.14.0.min.js', 'deps/react@16.14.0.min.js', 'dash-renderer/build/dash_renderer.min.js.map', 'dcc/async-plotlyjs.js.map', 'dash_table/async-export.js.map', 'dcc/async-mathjax.js.map', 'dash_table/bundle.js', 'dcc/dash_core_components.js.map', 'dcc/async-upload.js', 'dcc/async-slider.js.map', 'deps/polyfill@7.12.1.min.js', 'dcc/async-dropdown.js.map', 'dash_table/async-highlight.js', 'dash-renderer/build/dash_renderer.min.js', 'html/dash_html_components.min.js', 'dcc/async-graph.js.map', 'dash_table/async-highlight.js.map', 'dash_table/bundle.js.map', 'dcc/async-dropdown.js', 'dash_table/async-export.js', 'dcc/async-markdown.js', 'dcc/async-upload.js.map', 'dcc/async-markdown.js.map', 'dcc/async-highlight.js.map', 'dcc/async-datepicker.js', 'html/dash_html_components.min.js.map', 'dcc/dash_core_components-shared.js', 'dcc/plotly.min.js', 'dash_table/async-table.js', 'dcc/async-datepicker.js.map', 'dash_table/async-table.js.map', 'dcc/async-graph.js', 'dcc/dash_core_components-shared.js.map', 'dcc/async-plotlyjs.js', 'dcc/async-mathjax.js', 'dcc/async-slider.js', 'dcc/async-highlight.js', 'deps/prop-types@15.8.1.min.js'}, 'dash_bootstrap_components': {'_components/dash_bootstrap_components.min.js'}, 'dash_ag_grid': {'dash_ag_grid.min.js.map', 'async-enterprise.js.map', 'async-enterprise.js', 'dash_ag_grid.min.js', 'async-community.js.map', 'async-community.js'}, 'dash_quill': {'async-Quill.js', 'async-Quill.js.map', 'dash_quill.min.js', 'dash_quill.min.js.map'}, 'dash_summernote': {'dash_summernote.min.js.map', 'dash_summernote.min.js'}})

**Comment by pip-install-python** [comment]
I've also noticed those errors, which seem to be with the dash summernote library. Looks like it doesn't affect functionality, but it might take away some font features. Just gotta figure out what those files should contain and where to place them in the project.
